// frontend/payroll-web/src/app/features/employees/pages/employee-detail/employee-detail-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { EmployeesApiService } from '../../services/employees-api.service';
import { Employee } from '../../models/employee.model';

@Component({
  selector: 'app-employee-detail-page',
  templateUrl: './employee-detail-page.component.html',
  styleUrls: ['./employee-detail-page.component.scss'],
})
export class EmployeeDetailPageComponent implements OnInit {
  employee?: Employee;

  constructor(private route: ActivatedRoute, private router: Router, private employeesApi: EmployeesApiService) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.employeesApi.getEmployee(id).subscribe(employee => (this.employee = employee));
    }
  }

  goBack(): void {
    this.router.navigate(['/employees']);
  }

  editEmployee(): void {
    if (this.employee) {
      this.router.navigate(['/employees', this.employee.id, 'edit']);
    }
  }
}

<div *ngIf="employee" class="card">
  <div class="card__header">
    <h2>{{ employee.firstName }} {{ employee.lastName }}</h2>
    <div class="actions">
      <button type="button" (click)="editEmployee()">Edit</button>
      <button type="button" (click)="goBack()">Back</button>
    </div>
  </div>
  <div class="card__body">
    <div class="row"><strong>Employee Code:</strong> {{ employee.employeeCode }}</div>
    <div class="row"><strong>NIC:</strong> {{ employee.nicNumber }}</div>
    <div class="row"><strong>Date of Birth:</strong> {{ employee.dateOfBirth | dateFormat }}</div>
    <div class="row"><strong>Gender:</strong> {{ employee.gender }}</div>
    <div class="row"><strong>Marital Status:</strong> {{ employee.maritalStatus }}</div>
    <div class="row"><strong>Employment Start:</strong> {{ employee.employmentStartDate | dateFormat }}</div>
    <div class="row"><strong>Probation End:</strong> {{ employee.probationEndDate | dateFormat }}</div>
    <div class="row"><strong>Confirmation Date:</strong> {{ employee.confirmationDate | dateFormat }}</div>
    <div class="row"><strong>Base Salary:</strong> {{ employee.baseSalary | number: '1.0-2' }}</div>
    <div class="row"><strong>Active:</strong> {{ employee.isActive ? 'Yes' : 'No' }}</div>
  </div>
</div>

// frontend/payroll-web/src/pages/employees/EmployeeDetailPage.tsx
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getEmployee } from "../../api/employeesApi";
import LoadingSpinner from "../../components/common/LoadingSpinner";
import { Employee } from "../../types/Employee";

const EmployeeDetailPage = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [employee, setEmployee] = useState<Employee | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchEmployee = async () => {
      if (!id) return;
      setLoading(true);
      setError(null);
      try {
        const response = await getEmployee(id);
        setEmployee(response);
      } catch (err) {
        setError((err as Error).message || "Failed to load employee");
      } finally {
        setLoading(false);
      }
    };

    fetchEmployee();
  }, [id]);

  if (!id) return <p>Employee not found.</p>;
  if (loading) return <LoadingSpinner />;
  if (error) return <div className="error">{error}</div>;
  if (!employee) return <p>Employee not found.</p>;

  return (
    <section>
      <div className="page-header">
        <h1>Employee Details</h1>
        <div className="page-actions">
          <button onClick={() => navigate(`/employees/${employee.id}/edit`)}>Edit</button>
          <button onClick={() => navigate("/employees")}>Back</button>
        </div>
      </div>

      <div className="detail-grid">
        <div>
          <strong>Employee Code:</strong> {employee.employeeCode}
        </div>
        <div>
          <strong>Name:</strong> {employee.firstName} {employee.lastName}
        </div>
        <div>
          <strong>Initials:</strong> {employee.initials || "-"}
        </div>
        <div>
          <strong>Calling Name:</strong> {employee.callingName || "-"}
        </div>
        <div>
          <strong>NIC:</strong> {employee.nicNumber}
        </div>
        <div>
          <strong>Date of Birth:</strong> {new Date(employee.dateOfBirth).toLocaleDateString()}
        </div>
        <div>
          <strong>Gender:</strong> {employee.gender}
        </div>
        <div>
          <strong>Marital Status:</strong> {employee.maritalStatus}
        </div>
        <div>
          <strong>Employment Start Date:</strong> {new Date(employee.employmentStartDate).toLocaleDateString()}
        </div>
        <div>
          <strong>Probation End Date:</strong>
          {employee.probationEndDate ? new Date(employee.probationEndDate).toLocaleDateString() : "-"}
        </div>
        <div>
          <strong>Confirmation Date:</strong>
          {employee.confirmationDate ? new Date(employee.confirmationDate).toLocaleDateString() : "-"}
        </div>
        <div>
          <strong>Base Salary:</strong> {employee.baseSalary.toLocaleString()}
        </div>
        <div>
          <strong>Status:</strong> {employee.isActive ? "Active" : "Inactive"}
        </div>
      </div>
    </section>
  );
};

export default EmployeeDetailPage;
